odpckan:
    image: docker.io/eeacms/odpckan:v1.0-rc1
    restart: always
    environment:
        - RABBITMQ_HOST=10.128.0.22
        - RABBITMQ_PORT=5672
        - CKAN_ADDRESS=https://open-data.europa.eu/en/data
        - SERVICES_EEA=http://www.eea.europa.eu/data-and-maps/data
        - SERVICES_SDS=http://semantic.eea.europa.eu/sparql
        - SERVICES_ODP=https://open-data.europa.eu/en/data/publisher/eea
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - ./.secret:/eea.odpckan/.secret:z
